name: Metrics
on:
  schedule: [{cron: "0 0 1 * *"}]
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/base.svg
          base: header, activity, metadata
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: (/≧▽≦)/ Update ${filename}
          commits_authoring: Floaterest
          extras_js: document.querySelectorAll('footer')?.forEach(f => f.remove())

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject > .items-wrapper{
              border-radius: 1em;
              border: 1px solid #5e5e5e;
              background-color: #0f0f0f;
              padding-bottom: 1em;
            }
            foreignObject > div > section{
              color: #f1f1f1;
            }
  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar.svg
          base: false
          output_action: none
          token: ${{ secrets.METRICS_TOKEN }}
          commits_authoring: Floaterest

          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year

          extras_css: |
            h1,h2,h3{
              color: #39c5bb;
            }
            foreignObject > .items-wrapper{
              border-radius: 1em;
              border: 1px solid #5e5e5e;
              background-color: #0f0f0f;
              padding-bottom: 1em;
            }
            foreignObject > div > section{
              color: #f1f1f1;
            }
      - name: Test
        run: tree
      - name: Update calendar
        run: python3 update.py metrics/calendar.svg

      - name: Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add .
          git commit -m "(/≧▽≦)/ Update metrics/calendar.svg"
          git push -f

